workflows:
  ios-workflow:
    name: iOS Test Build
    max_build_duration: 60
    environment:
      node: 22.14.0
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install dependencies with legacy peer deps
        script: |
          npm install --legacy-peer-deps
          
      - name: Fix ajv dependency issue
        script: |
          npm install ajv@^8.0.0 --legacy-peer-deps
          npm install ajv-keywords@^5.0.0 --legacy-peer-deps
          
      - name: Install Capacitor iOS
        script: |
          npm install @capacitor/ios --legacy-peer-deps
          
      - name: Build web assets (ignore warnings)
        script: |
          CI=false npm run build
          
      - name: Sync Capacitor (keep existing iOS project)
        script: |
          npx cap sync ios

      - name: Update iOS deployment target and clean pods
        script: |
          cd ios/App
          
          # Update deployment target in project file
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' App.xcodeproj/project.pbxproj
          
          # Update Podfile platform version
          sed -i '' "s/platform :ios, [0-9.]*/platform :ios, '14.0'/g" Podfile

           # Clean existing pods
            rm -rf Pods
            rm -f Podfile.lock
          
          cd ../..
          
      - name: Sync Capacitor with clean pods
        script: |
          npx cap sync ios
          
      - name: Build IPA
        script: |
          cd ios/App
          
          # Build archive
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          # Create IPA
          mkdir -p Payload
          cp -r build/App.xcarchive/Products/Applications/App.app Payload/
          zip -r $CM_BUILD_DIR/MediCureOn.ipa Payload
          
    artifacts:
      - $CM_BUILD_DIR/MediCureOn.ipa