workflows:
  ios-workflow:
    name: iOS Test Build
    max_build_duration: 60
    environment:
      node: 22.14.0
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install dependencies with legacy peer deps
        script: |
          npm install --legacy-peer-deps
          
      - name: Fix ajv dependency issue
        script: |
          npm install ajv@^8.0.0 --legacy-peer-deps
          npm install ajv-keywords@^5.0.0 --legacy-peer-deps
          
      - name: Install Capacitor iOS
        script: |
          npm install @capacitor/ios --legacy-peer-deps
          
      - name: Build web assets (ignore warnings)
        script: |
          CI=false npm run build
          
      - name: Update Capacitor config for iOS 13.0
        script: |
          # Update capacitor.config.json to set minimum iOS version
          node -e "
          const fs = require('fs');
          const config = JSON.parse(fs.readFileSync('capacitor.config.json', 'utf8'));
          if (!config.ios) config.ios = {};
          config.ios.minVersion = '13.0';
          fs.writeFileSync('capacitor.config.json', JSON.stringify(config, null, 2));
          console.log('Updated capacitor.config.json:', JSON.stringify(config, null, 2));
          "
          
      - name: Add iOS platform with correct deployment target
        script: |
          # Set environment variable for Capacitor
          export CAPACITOR_IOS_MIN_VERSION=13.0
          
          # Add iOS platform
          npx cap add ios || echo "iOS already added"
          
          # Ensure the deployment target is set in the project
          if [ -d "ios/App" ]; then
            cd ios/App
            
            # Update the Xcode project deployment target
            if [ -f "App.xcodeproj/project.pbxproj" ]; then
              sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' App.xcodeproj/project.pbxproj
              echo "Updated project.pbxproj deployment target"
            fi
            
            cd ../..
          fi
          
      - name: Sync Capacitor with iOS 13.0
        script: |
          # Set environment variable for pod install
          export CAPACITOR_IOS_MIN_VERSION=13.0
          
          # Run sync which will generate Podfile with correct platform version
          npx cap sync ios
          
          # Double-check and fix Podfile if needed
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            # Ensure platform is set to iOS 13.0
            if ! grep -q "platform :ios, '13.0'" Podfile; then
              sed -i '' "1s/^/platform :ios, '13.0'\n/" Podfile
              echo "Added platform iOS 13.0 to Podfile"
            fi
            
            # Run pod install again if we modified the Podfile
            pod install
            cd ../..
          fi
          
      - name: Build unsigned IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath build \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
          # Create IPA for testing
          mkdir -p Payload
          cp -r build/App.xcarchive/Products/Applications/App.app Payload/
          zip -r $CM_BUILD_DIR/MediCureOn.ipa Payload
          
    artifacts:
      - $CM_BUILD_DIR/MediCureOn.ipa
      - ios/App/build/**/*.app